version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
