# Generated by Django 5.0.6 on 2024-09-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='parent_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='departure.departure'),
        ),
    ]
